### PR TITLE
Added and implemented a basic config system and a default logger

### PR DESCRIPTION
**Pull request by gregseb**
Config system seems pretty easy and convenient.

I declared a logger and even tried using it, however the default handler of stderr doesn't appear in our python console output.  Would be nice to figure out something that does.

### CODE REVIEW

**Comment by gregseb** [comment]
Also, look at that, attempting to parse requirements.txt in setup.py actually breaks travis builds.  Lets fix that in this pull request.

**Comment by gregseb** [comment]
Ah, derp, forgot to update MANIFEST.in..  Fixing

**Comment by gregseb** [comment]
Fixes #6

**Comment by spatialbits** [comment]
I don't see the change that fixes the requirements parse for travis builds. I do see that travis runs ok though.

**Pull request merged**
