### PR TITLE
First working prototype

### PR DESCRIPTION
**Pull request by spatialbits**
fleshing in geomark class and tests.

### CODE REVIEW

**Comment by gregseb** [comment]
What's the goal of this PR/branch?  Is this supposed to be the first prototype working version or are you just stubbing in the structure?

**Comment by gregseb** [comment]
Okay, let's use this PR/Branch as the main devleopment hub until we feel we have arrived where we want.

**Comment by gregseb** [comment]
Please keep an eye on the cards located [here](https://github.com/greg-and-adam/python-geomark/projects/1#card-6173580) and move them as necessary to keep track of the progress of each feature.

**Comment by gregseb** [comment]
I would like to request we merge this branch so that the code can be put in a condition that is easier for us to split up the work in different branches.

**Comment by spatialbits** [comment]
being a first blush I don't think we can say it's stable, but it is functional. Merge away @gregseb !

**Comment by gregseb** [comment]
Alright, I'm doing it!

**Pull request merged**
